export enum ErrorCode {
  // General
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  CONFLICT = 'CONFLICT',

  // Authentication
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  INVALID_VERIFICATION_TOKEN = 'INVALID_VERIFICATION_TOKEN',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  INVALID_RESET_TOKEN = 'INVALID_RESET_TOKEN',
  INVALID_CURRENT_PASSWORD = 'INVALID_CURRENT_PASSWORD',
  INVALID_CODE = 'INVALID_CODE',
  TOO_MANY_ATTEMPTS = 'TOO_MANY_ATTEMPTS',

  // User
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_INACTIVE = 'USER_INACTIVE',
  USER_BANNED = 'USER_BANNED',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  EMAIL_ALREADY_VERIFIED = 'EMAIL_ALREADY_VERIFIED',

  // File
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_ALLOWED = 'FILE_TYPE_NOT_ALLOWED',
  FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED',

  // External Services
  SMS_SERVICE_ERROR = 'SMS_SERVICE_ERROR',
  MAIL_SERVICE_ERROR = 'MAIL_SERVICE_ERROR',
  STORAGE_SERVICE_ERROR = 'STORAGE_SERVICE_ERROR',
  PUSH_NOTIFICATION_ERROR = 'PUSH_NOTIFICATION_ERROR',

  // Database
  DATABASE_ERROR = 'DATABASE_ERROR',
  QUERY_FAILED = 'QUERY_FAILED',

  // Multi-Tenancy
  CLIENT_NOT_FOUND = 'CLIENT_NOT_FOUND',
  CLIENT_INACTIVE = 'CLIENT_INACTIVE',
  CLIENT_ID_MISSING = 'CLIENT_ID_MISSING',

  // Calls
  CALL_NOT_FOUND = 'CALL_NOT_FOUND',
  CALL_ALREADY_PROCESSED = 'CALL_ALREADY_PROCESSED',
  USER_PHONE_MISSING = 'USER_PHONE_MISSING',
  INVALID_SCHEDULED_TIME = 'INVALID_SCHEDULED_TIME',
  INSUFFICIENT_CREDITS = 'INSUFFICIENT_CREDITS',

  // System Settings
  SETTING_NOT_FOUND = 'SETTING_NOT_FOUND',
}
